name: Test
on: push
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: git checkout
        uses: actions/checkout@V4

      - name: Hello
        run: echo "Test msg"
        
      - name: List files
        run: ls