name: Test
on: push
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: git checkout
        uses: actions/checkout@V4

      - name: List & Read Files
        run: |
            echo "Test msg"
            ls -ltra
            cat readme.md
        
      - name: List files
        run: ls