name: Test
on: push
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@test

      - name: Hello
        run: echo "Test msg"
        
      - name: List files
        run: ls